version: '3'

services:
  config-server:
    image: conf:1.0  # Use the same image as in the running container for config server
    container_name: conf11
    ports:
      - "8881:8888"


  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  t
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5


    depends_on:
      - config-server

