eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10      # Time interval (in seconds) for clients to renew their lease with Eureka
    leaseExpirationDurationInSeconds: 30   # Duration (in seconds) after which an instance is considered down if no renewal happens
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

spring:
  application:
    name: discovery
