eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8095

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/users/**
        - id: rendez-vous
          uri: lb://rendez-vous
          predicates:
            - Path=/api/rendez-vous/**
        - id: DossierMedical
          uri: lb://DossierMedical
          predicates:
            - Path=/api/DossierMedical/**
        - id: Blogs
          uri: lb://Blogs
          predicates:
            - Path=/api/blog/**
        - id: Avis
          uri: lb://Avis
          predicates:
            - Path=/api/avis/**