eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8095
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/users/**
        - id: rendez-vous
          uri: http://localhost:8091
          predicates:
            - Path=/api/rendez-vous/**
        - id: dossiermedical
          uri: http://localhost:8092
          predicates:
            - Path=/api/DossierMedical/**
        - id: blogs
          uri: http://localhost:8093
          predicates:
            - Path=/api/blog/**
        - id: avis
          uri: http://localhost:8094
          predicates:
            - Path=/api/avis/**
