eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZne: http://localhost:8761/eureka

server:
  port: 8222


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/micro-services"
          jwk-set-uri: "http://localhost:8080/realms/micro-services/protocol/openid-connect/certs"
  main:
    web-application-type: reactive
    allow-bean-definition-overriding=true:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/users/**
        - id: rendez-vous
          uri: http://localhost:8091
          predicates:
            - Path=/api/rendez-vous/**
        - id: DossierMedical
          uri: http://localhost:8092
          predicates:
            - Path=/api/DossierMedical/**
        - id: Blogs
          uri: http://localhost:8093
          predicates:
            - Path=/api/blog/**
        - id: Avis
          uri: http://localhost:8094
          predicates:
            - Path=/api/avis/**
