eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZne: http://localhost:8761/eureka

spring:
  application:
    name: Rendez-vous

  datasource:
    url: jdbc:h2:mem:RDV
    driver-class-name: org.h2.Driver
    username: sa
    password:

    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update

    h2:
      console:
        enabled: true
        path: /h2-console




server:
  port: 8091